### ISSUE TITLE
Lien démo non fonctionnel

### ISSUE THREAD

**Issue by rdubigny** [assurance-maladie-digital/api-droits-fs-exemple-php#1]
Bonjour,

Le lien vers l'application de démo ne fonctionne pas dans le README.md :

https://github.com/assurance-maladie-digital/api-droits-fs-exemple-php/blob/36a50949e1794259055afe3896bb5795588a0108/README.md#L15-L19

Merci !

**Comment by sboulkour** [comment]
Bonjour,

Les environnements de démo ne sont plus dispo suite à la fin de l'offre d'hébergement utilisée il y a deux ans. Je pense que nous ne remettrons pas de démo en ligne pour l'instant.
